AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.13
    Timeout: 30
    MemorySize: 256

Resources:
  # DynamoDB Table for duplicate prevention
  JiraGithubSyncTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: jira-github-sync-state
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: jira_issue_key
          AttributeType: S
      KeySchema:
        - AttributeName: jira_issue_key
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  JiraWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: jira_handler/
      Handler: app.lambda_handler
      Environment:
        Variables:
          GITHUB_OWNER: Nuwantha57
          GITHUB_REPO: jira-sync-test
          JIRA_BASE_URL: https://nuwanthapiumal57.atlassian.net
          TARGET_LABEL: sync-to-github
          SECRET_NAME: jira-github-integration
          DYNAMODB_TABLE: jira-github-sync-state
          USER_MAPPING: "712020:bb0cbe76-91d7-4797-bc17-cb969d3ddb7e:NuwanthaPiumal"  # Format: jira_accountid:github_user OR jira_email:github_user (comma-separated)
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:jira-github-integration*
        - DynamoDBCrudPolicy:
            TableName: !Ref JiraGithubSyncTable
      Events:
        JiraWebhook:
          Type: Api
          Properties:
            Path: /webhook
            Method: post

  GitHubWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: jira_handler/
      Handler: github_webhook_handler.lambda_handler
      Environment:
        Variables:
          GITHUB_OWNER: Nuwantha57
          GITHUB_REPO: jira-sync-test
          JIRA_BASE_URL: https://nuwanthapiumal57.atlassian.net
          SECRET_NAME: jira-github-integration
          DYNAMODB_TABLE: jira-github-sync-state
          USER_MAPPING: "712020:bb0cbe76-91d7-4797-bc17-cb969d3ddb7e:NuwanthaPiumal"
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:jira-github-integration*
        - DynamoDBCrudPolicy:
            TableName: !Ref JiraGithubSyncTable
      Events:
        GitHubWebhook:
          Type: Api
          Properties:
            Path: /github-webhook
            Method: post

Outputs:
  JiraWebhookUrl:
    Description: "API Gateway endpoint URL for Jira webhook"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook"
  
  GitHubWebhookUrl:
    Description: "API Gateway endpoint URL for GitHub webhook"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/github-webhook"

